### ISSUE TITLE
Code Transpilation to Ruby (Help Wanted)

### ISSUE THREAD

**Issue by khoaxuantu** [krahets/hello-algo#1253]
We appreciate your help in transpiling the code to Ruby.

Please check the contribution guidelines at #15.

For the convention, we are following the [Ruby Style Guide](https://rubystyle.guide/) and the comments as follows:

```rb
### Heading comment ###

# Single comment

# Multi-line comment
# Multi-line comment
# Multi-line comment
```

---

- [x] Computational complexity #1212 

- - [x] Time complexity #1212 
- - [x] Space complexity #1212 
- - [x] Space time tradeoff #1212 

- [x] Data structure #1227 

- [x] Array and linked list #1158 

- - [x] Array #1158 
- - [x] Linked list #1158 
- - [x] List #1158 

- [x] Stack and queue #1230 

- - [x] Stack #1230 
- - [x] Queue #1230 
- - [x] Deque #1230 

- [x] Hashing #1276 

- - [x] Hash map #1276  
- - [x] Hash collision #1276  
- - [x] Hash algorithm #1276  

- [x] Tree #1288 

- - [x] Binary tree #1288 
- - [x] Binary tree types #1288 
- - [x] Array binary tree #1288 
- - [x] AVL tree #1288 

- [x] Heap #1300

- - [x] Max heap #1300 
- - [x] Top K #1300 

- [x] Graph #1303 

- - [x] Graph operations #1303 
- - [x] Graph traversal #1303 

- [x] Searching #1262 

- - [x] Linear search #1262 
- - [x] Binary search #1262 
- - [x] Binary search edge #1262 
- - [x] Hash search #1262 

- [x] Sorting

- - [x] Selection sort  #1333 
- - [x] Bubble sort  #1333 
- - [x] Insertion sort #1222 
- - [x] Quick sort #1223 
- - [x] Merge sort #1261 
- - [x] Heap sort #1260 
- - [x] Bucket sort #1285 
- - [x] Counting sort #1333 
- - [x] Radix sort #1333 

- [x] Greedy #1350

- [x] Divide and conquer #1361 

- - [x] Binary search by recursion #1361 
- - [x] Build tree #1361 
- - [x] Hanota #1361 

- [x] Backtracking #1373 

- - [x] Preorder traversal compact #1373 
- - [x] Permutations #1373 
- - [x] Subset sum #1373 
- - [x] N-Queens #1373 

- [x] Dynamic programming #1378 

- - [x] Climbing stairs #1378 
- - [x] Coin change #1378 
- - [x] Knapsack #1378 
- - [x] Edit distance #1378 
- - [x] Min path sum #1378

**Comment by bluebean-cloud** [comment]
I would like to do the **searching** part.

After I finish one part, I will go on to claim the next part.

I will finish it at this week.

**Comment by khoaxuantu** [comment]
I'm gonna do chapter hashing, it is expected to have a new PR created in one or two days :rocket:

**Comment by bluebean-cloud** [comment]
I'm gonna do chapter heap.

New PR will be created in next weeks 🚀

**Comment by martinx** [comment]
Let me do the rest of `Sorting` chapter

**Comment by martinx** [comment]
New PR #1282 for `selection sort`

**Comment by martinx** [comment]
New PR #1283 for `bubble sort`

**Comment by khoaxuantu** [comment]
I'm going to do chapter tree, a new PR will be created soon :rocket:

**Comment by khoaxuantu** [comment]
I will start doing chapter graph today, expect to have a new PR this weekend 🚀

**Comment by khoaxuantu** [comment]
@krahets I have checked all the topics again and seen that we have done the Ruby code transpilation 🥳 Thanks for helping me contributing so far!

And of course, thanks @bluebean-cloud and @martinx for your great contributions!

#1379

**Comment by krahets** [comment]
@khoaxuantu Thank you for the great contribution! Look forward to continuing to work with you to make hello-algo better!
