### ISSUE TITLE
Code Transpilation to C (Help Wanted)

### ISSUE THREAD

**Issue by Gonglja** [krahets/hello-algo#425]
We need your help translating the code to C.

Please check the contribution guidelines at #15 

## TODO List

- [x] Computational Complexity

- - [x] Time Complexity #204 (@sjinzh)

- - [x] Space Complexity #456 (@Gonglja )

- - [x] Space Time Tradeoff #299 (@Reanon) 

- [x] Array And LinkedList

- - [x] Array #154 (@MolDuM)

- - [x] LinkedList #244 (@Gonglja)

- - [x] List #253 (@Gonglja)

- [x] Stack And Queue

- - [x] Stack #289 #299 (@Gonglja , @Reanon , @krahets )

- - [x] Queue #300 #413 (@Gonglja , @krahets )

- - [x] Deque #412 (@Gonglja)

- [x] Hashing

- - [x] Hash Map #424 (@Guanngxu )

- - [x] Hash Collision

- - [x] Hash Algorithm #730  (@Gonglja )

- [x] Tree

- - [x] Binary Tree #234 (@Reanon)

- - [x] Binary Tree Types 

- - [x] Array Binary Tree #664 (@Gonglja )

- - [x] Binary Search Tree #234 (@Reanon)

- - [x] AVL Tree #260 (@Reanon)

- [x] Heap

- - [x] Max Heap #261 (@Reanon )

- - [x] Top K

- [x] Graph 

- - [x] Graph Operations

- - [x] Graph Traversal #601 (@NI-SW )

- [x] Searching

- - [x] Linear Search #426 (@Guanngxu )

- - [x] Binary Search #426 (@Guanngxu )

- - [x] Hash Search #458 (Gonglja)

- [x] Sorting

- - [x]  Selection Sort

- - [x] Bubble Sort #166 (@L-Super )

- - [x] Insertion Sort #191 (@L-Super )

- - [x] Quick Sort #273 (@Reanon )

- - [x] Merge Sort #434 (@Guanngxu )

- - [x] Heap Sort

- - [x] Bucket Sort

- - [x] Counting Sort #430 (@Reanon @Guanngxu )

- - [x] Radix Sort #273 (@Reanon )

- [x] Divide and Conquer

- - [x] Binary Search by Recursion 

- - [x] Build Tree 

- - [x] Hanota 

- [x] Backtracking

- - [x] Preorder Traversal Compact 

- - [x] Permutations

- - [x] Subset Sum

- - [x] N Queens

**Comment by MG-Guan** [comment]
I've shot a PR for hashing part. https://github.com/krahets/hello-algo/pull/429

**Comment by what-is-me** [comment]
please delete [add chapter_sorting by dart](https://github.com/krahets/hello-algo/pull/366) (@what-is-me @krahets )from this Issue. 
dart is not c.
Thanks.

**Comment by Gonglja** [comment]
> please delete [add chapter_sorting by dart](https://github.com/krahets/hello-algo/pull/366) (@what-is-me @krahets )from this Issue. dart is not c. Thanks.

Thanks @what-is-me , updated
Check the history of the file at that time, add this part if there is a change history

**Comment by Gonglja** [comment]
> I've shot a PR for hashing part. #429

OK, thanks @MG-Guan

**Comment by Gonglja** [comment]
> I've shot a PR for hashing part. #429

Thanks @MG-Guan, but the code does not match the description [in the text](https://www.hello-algo.com/chapter_hashing/hash_map/#613), please refer to the implementation of array_hashing_map in other languages

**Comment by MG-Guan** [comment]
> > I've shot a PR for hashing part. #429
> 
> Thanks @MG-Guan, but the code does not match the description [in the text](https://www.hello-algo.com/chapter_hashing/hash_map/#613), please refer to the implementation of array_hashing_map in other languages

Got it. Thanks for the replay : )

**Comment by huawuque404** [comment]
@krahets Hello,I have found that the newly added dynamic planning chapter does not yet have C language code. Can I participate in C language code translation?

**Comment by krahets** [comment]
@huawuque404 C code contributions are welcome!

**Comment by lhxsm** [comment]
I've shot a PR for N queens. https://github.com/krahets/hello-algo/pull/774

**Comment by krahets** [comment]
Closed because the 1st edition has been completed! Thank you for the great work!
